version: 2

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}}
            - yarn-packages-
      - run:
          name: Install Yarn Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}}
          paths:
            - .yarn
            - node_modules
      - run:
          name: Create .env
          command: |
            echo "BOT_OWNERS=${BOT_OWNERS}
            BOT_TIMEZONE=${BOT_TIMEZONE}
            DISCORD_TOKEN=${DISCORD_TOKEN}
            DISCORD_NICKNAME=${DISCORD_NICKNAME}" > ~/project/.env
      - run:
          name: Build
          command: yarn build
      - run:
          name: Move node_modules
          command: mv -t ~/project/dist ~/project/package.json ~/project/yarn.lock ~/project/.env
      - save_cache:
          name: Save Application Cache
          key: application-{{ .Revision }}
          paths:
            - dist

  deploy:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - application-{{ .Revision }}
            - application-
      - add_ssh_keys:
          fingerprints:
            - "${REMOTE_HOST}"
      - run:
          name: Install Dependencies
          command: sudo apt-get update && sudo apt-get -y install ssh rsync
      - run:
          name: Create SSH Files
          command: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      - run:
          name: Create Known Hosts
          command: ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -Oazvhc --delete --exclude -e '.data/*' ssh ~/project/dist/ tutelary@$REMOTE_HOST:/srv/tutelary.scottgeary.me/bot
              ssh -t tutelary@$REMOTE_HOST "cd ~/www/bot; yarn install"
              ssh -t tutelary@$REMOTE_HOST "pm2 restart index"
            else
              echo "Not master branch, dry run only"
            fi
      - store_artifacts:
          path: ~/project/dist
          destination: tutelary

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build